version: '3.9'

services:
  app:
    build: ./app
    command: npm run dev
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      
  db:
    image: postgres:15.3
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
